apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "odin.fullname" . }}
  labels:
    {{- include "odin.labels" . | nindent 4 }}
    component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "odin.selectorLabels" . | nindent 6 }}
      component: postgres
  template:
    metadata:
      labels:
        {{- include "odin.labels" . | nindent 8 }}
        component: postgres
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: postgres
          env:
            - name: POSTGRESQL_VOLUME_DIR
              value: {{ .Values.pgvolume }}
            - name: PGDATA
              value: {{ .Values.pgdata }}
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap }}
                  key: db_user
            - name: DB_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap }}
                  key: db_port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap }}
                  key: db_name
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret }}
                  key: password
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  {{- with .Values.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 12 }}
  {{- end }}
