apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odin.fullname" . }}-cm
  labels:
    {{- include "odin.labels" . | nindent 4 }}
data:
  clusters.yaml: |
  {{- toYaml .Values.odin.clusters_conf | nindent 4 }}
  db_user: {{ .Values.odin.database.user | quote }}
  db_host: {{ .Values.odin.database.host | quote }}
  db_port: {{ .Values.odin.database.port | quote }}
  db_name: {{ .Values.odin.database.name | quote }}