apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "odin.fullname" . }}-private
  labels:
    {{- include "odin.labels" . | nindent 4 }}
spec:
  httpVersions:
    - http/1.1
  ingressClassName: {{ .Values.odin.httpProxy.type }}
  routes:
    - enableWebsockets: true
      loadBalancerPolicy:
        strategy: RoundRobin
      services:
        - name: {{ include "odin.fullname" . }}
          port: 8000
          weight: 100
      timeoutPolicy:
        idleConnection: 15s
        response: 30s
  virtualhost:
     {{- toYaml .Values.odin.httpProxy.virtualhost | nindent 4 }}


---

{{- if .Values.odin.httpProxy.enabled -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "odin.fullname" . }}
  labels:
    {{- include "odin.labels" . | nindent 4 }}
spec:
  httpVersions:
    - http/1.1
  ingressClassName: {{ .Values.odin.httpProxy.type }}
  routes:
    - enableWebsockets: true
      loadBalancerPolicy:
        strategy: RoundRobin
      services:
        - name: {{ include "odin.fullname" . }}
          port: 8000
          weight: 100
      timeoutPolicy:
        idleConnection: 15s
        response: 30s
  virtualhost:
    fqdn: odin.snapp.tech
    tls:
      enableFallbackCertificate: true
      secretName: devops-certificates/snapp-tech-tls
{{- end }}
