apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odin.fullname" . }}-secret
  labels:
    {{- include "odin.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.odin.database.pass | default "" | b64enc }}
  {{- range $key, $value := .Values.odin.tokens }}
  {{ $key }}: "{{ $value }}"
  {{- end }}