apiVersion: v1
kind: Service
metadata:
  name: {{ include "odin.fullname" . }}
  labels:
    {{- include "odin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.odin.service.type }}
  ports:
    - port: {{ .Values.odin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "odin.selectorLabels" . | nindent 4 }}
